const mongoose=require('mongoose');
const orderItemSchema=new mongoose.Schema({
    productId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Product",
        required:true
    },
    variantId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Variant",
        required:true
    },
    quantity:{
        type:Number,
        required:true
    },
    price:{
        type:Number,
        required:true
    }
});

const orderSchema=new mongoose.Schema({
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User',
        required:true
    },
    address:{
        fullName:String,
        phone:String,
        street:String,
        city:String,
        state:String,
        pincode:String
    },
    items:[orderItemSchema],
    paymentMethod:{
        type:String,
        enum:['COD'],
        default:'COD'
    },
    subtotal:{
        type:Number,
        required:true
    },
    total:{
        type:Number,
        required:true
    },
    status:{
        type:String,
        enum:['Pending','Shipped','Delivered','Cancelled'],
        default:'pending'
    },
    createdAt:{
        type:Date,
        default:Date.now
    }
})

module.exports=mongoose.model('Order',orderSchema);